job1:

    image: python:2.7

    before_script:

        - apt-get update
        - apt-get install -y software-properties-common
        - add-apt-repository -y ppa:freecad-maintainers/freecad-stable
        - apt-get update
        - apt-get install -y freecad

    script:

        - git clone https://gitlab.com/damianCaceres/slopedplanestest
        - mkdir .FreeCAD
        - cd .FreeCAD
        - mkdir Mod
        - cd Mod
        - mkdir SlopedPlanesMacro
