job1:

    image: ubuntu:latest

    before_script:

        - cat /etc/os-release
        - apt-get update
        - add-apt-repository -y ppa:freecad-maintainers/freecad-daily
        - ls /etc/apt/sources.list.d
        - cat /etc/apt/sources.list.d/freecad-maintainers-ubuntu-freecad-daily-disco.list
        - apt-key list
        - apt-get update
        - apt-get install -y freecad-daily

    script:

        - git clone https://gitlab.com/damianCaceres/slopedplanestest
        - mkdir .FreeCAD
        - cd .FreeCAD
        - mkdir Mod
        - cd Mod
        - mkdir SlopedPlanesMacro
