language: python
python:
    - "2.7"
before_install:
    - sudo add-apt-repository -y ppa:freecad-maintainers/freecad-daily
    - sudo apt-get update
    - sudo apt-get install -y freecad-daily
    - pwd
    - dir --all
    - which freecad-daily
script:
    - cd /home/travis
    - git clone https://github.com/caceres/SlopedPlanesTest.git
    - mkdir .FreeCAD
    - cd .FreeCAD
    - mkdir Mod
    - cd Mod
    - mkdir SlopedPlanesMacro
    - cp /home/travis/build/caceres/SlopedPlanesMacro/* /home/travis/.FreeCAD/Mod/SlopedPlanesMacro
    - cd /home/travis/build/caceres/SlopedPlanesMacro
    - python pytest.py