language: python
python:
    - "2.7"
before_install:
    - sudo add-apt-repository -y ppa:freecad-maintainers/freecad-daily
    - sudo apt-get update
    - sudo apt-get install -y freecad-daily
    - dir
script:
    - python pytest.py