language: python
python:
    - "2.7"
before_install:
    - sudo add-apt-repository -y ppa:freecad-maintainers/freecad-daily
    - sudo apt-get update
    - sudo apt-get install -y freecad-daily
    - pwd
    - dir
    - which freecad-daily
    -cd /home/travis/.FreeCAD
    - dir
    - mkdir Mod
    - cd Mod
    - mkdir SlopedPlanesMacro
    - cp --force /home/travis/build/caceres/SlopedPlanesMacro/* /home/travis/.FreeCAD/Mod/SlopedPlanesMacro
script:
    - python pytest.py